### ISSUE TITLE
gtrace generates nothing

### ISSUE THREAD

**Issue by kor44** [gobwas/gtrace#2]
Hello!
I have tried to generate example by following command `go generate ./examples/...`,
but it generates only this
```go
// Code generated by gtrace. DO NOT EDIT.

package main
```

**Comment by gobwas** [comment]
Hello @kor44,

Did you tag some structures with `//gtrace:gen`?

**Comment by kor44** [comment]
> 
> 
> Hello @kor44,
> 
> Did you tag some structures with `//gtrace:gen`?

I tried to generate example from gtrace repositary

**Comment by gobwas** [comment]
So do you have the directive `//gtrace:gen`? If yes, can you please run the `gtrace -v ./path/to/your/file.go`?

**Comment by kor44** [comment]
```
d:\path_go\src\github.com\gobwas\gtrace
$ gtrace -v .\examples\pinger\main.go
main.go:68: source file: .\examples\pinger\main.go
main.go:69: package files: []
// Code generated by gtrace. DO NOT EDIT.

package

main.go:243: OK

d:\path_go\src\github.com\gobwas\gtrace
$ go version
go version go1.14.1 windows/amd64

d:\path_go\src\github.com\gobwas\gtrace
$
```

**Comment by gobwas** [comment]
Hey @kor44,

Now its clear to me, thank you! I’ll fix it today’s evening.

**Comment by gobwas** [comment]
Hey @kor44,

Looks like it fixed now for Windows!

Thanks for reporting! 🍻
